version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - yum install -y wget unzip
      - wget https://releases.hashicorp.com/terraform/1.9.3/terraform_1.9.3_linux_amd64.zip
      - unzip terraform_1.9.3_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Making install script executable"
      - chmod +x scripts/install_dev_tools.sh

  build:
    commands:
      - echo "Running terraform init"
      - terraform init
      - echo "Running terraform apply"
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Fetching EC2 instance ID"
      - INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Project,Values=terraform-automation" --query "Reservations[0].Instances[0].InstanceId" --output text)
      - echo "Instance ID = $INSTANCE_ID"
      - echo "Fetching EC2 console output"
      - aws ec2 get-console-output --instance-id "$INSTANCE_ID" --output text
      - echo "✅ Finished printing output"
