version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum install -y wget unzip
      - wget https://releases.hashicorp.com/terraform/1.9.3/terraform_1.9.3_linux_amd64.zip
      - unzip terraform_1.9.3_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Setting executable permission for install script..."
      - chmod +x scripts/install_dev_tools.sh

  build:
    commands:
      - echo "Starting Terraform Init"
      - terraform init
      - echo "Applying Terraform"
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Fetching EC2 console output for installed versions..."
      - INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Project,Values=terraform-automation" --query "Reservations[].Instances[].InstanceId" --output text)
      - aws ec2 get-console-output --instance-id $INSTANCE_ID --output text
      - echo "✅ Printed software versions from EC2."
